### ISSUE TITLE
.\Downloader.exe' is not recognized. Please help

### ISSUE THREAD

**Issue by sunny9t1** [Mikyan0207/CyberDownloader#2]
This is the Error:
.\Downloader.exe : The term '.\Downloader.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ .\Downloader.exe -i
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Downloader.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Mikyan0207** [comment]
Hi,
The executable must be in the folder where you run the command or it will not be found.
If this is not the problem, can you share a full screen shot of your terminal?

**Comment by sunny9t1** [comment]
there are all .cs files no single .exe files in the zip folder i downloaded. Am i missing something

**Comment by Mikyan0207** [comment]
You need to download `Downloader.exe` from here: https://github.com/Mikyan0207/CyberDownloader/releases/tag/v1.1.0

**Comment by sunny9t1** [comment]
okay it is working now.. thank you.. i have only downloaded the zip files... Thanks again for helping

**Comment by Mikyan0207** [comment]
No problem, I'm closing this issue if everything is fine now
